environment:
  name: prod
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/client-db
    username: root
    password: root_password_123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
server:
  port : 8081
logging:
  level:
    org.springframework: info
