environment:
    name: dev
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thinka_db
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port : 8081
logging:
  level:
    org.springframework: ERROR
#microservices:
#  clients:
#    email:
#      url: http://localhost:8089/
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: martin@srweb.cl
#    password: Martin212.365
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true